all:
  # all attributes below are set on the Doctrine_Manager instance
  attributes:
    # export sql (none, tables, constraints, all)
    export:  all

    # enable doctrine side validation (true, false)
    validate: false
    
    # recursive merge functions from different directories/plugins
    recursive_merge_fixtures: true

    # turn on automatic accessor override functionality
    # for accessor and mutator overriding
    auto_accessor_override: true

    # enable quoting
    quote_identifier: false
    
    # enable autoloading of table class
    autoload_table_classes: true

  listeners:        []
  record_listeners: []

# Configuration for specific connection names 
#  connections:
#    doctrine:
#      attributes:
#        export: all
#      listeners:        []
#      record_listeners: []